### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by Melzita** [fagnerpc/Alekfull-ARTFLIX#1]
In the emuelec 3.6 version, the system description texts do not appear!`
![WhatsApp Image 2020-06-23 at 19 16 54](https://user-images.githubusercontent.com/40698143/85471589-0823d580-b587-11ea-8629-7c90f5999e4a.jpeg)

`

**Comment by fagnerpc** [comment]
Update Emuelec to 3.7.
This error on EmulationStation was corrected in this Emuelec update - isn't related to the theme code.
