### ISSUE TITLE
Wrong names for Batocera V33

### ISSUE THREAD

**Issue by KevinLeenders** [fagnerpc/Alekfull-ARTFLIX#15]
Hi,

Batocera V33 has these's naming conflicts:

**Theme Name, Batocera name**
bbcmicro, bbc
astrocade, astrocde
creativision, crvision

U must rename these folders:
Alekfull-ARTFLIX\bbcmicro >Alekfull-ARTFLIX\bbc
Alekfull-ARTFLIX\astrocade > Alekfull-ARTFLIX\astrocde
Alekfull-ARTFLIX\creativision > Alekfull-ARTFLIX\crvision

To corrosponding Batocera name

U must rename these files:
Alekfull-ARTFLIX\assets\arts\(540,720)\bbcmicro.png > Alekfull-ARTFLIX\assets\arts\(540,720)\bbc.png
Alekfull-ARTFLIX\assets\arts\(540,720)\astrocade.png > Alekfull-ARTFLIX\assets\arts\(540,720)\astrocde.png
Alekfull-ARTFLIX\assets\arts\(540,720)\creativision.png > Alekfull-ARTFLIX\assets\arts\(540,720)\crvision.png

Alekfull-ARTFLIX\assets\logos\bbcmicro.png >Alekfull-ARTFLIX\assets\logos\bbc.png
Alekfull-ARTFLIX\assets\logos\astrocade.png > Alekfull-ARTFLIX\assets\logos\astrocde.png
Alekfull-ARTFLIX\assets\logos\creativision.png > Alekfull-ARTFLIX\assets\logos\crvision.png

Or Copy so both exist.

**Comment by fagnerpc** [comment]
Hi,
I made new systems with new names to be compatible with Batocera V33.

Thanks for the feedback.
