### ISSUE TITLE
Top game logos cropped.

### ISSUE THREAD

**Issue by frodo19** [fagnerpc/Alekfull-ARTFLIX#16]
Some top logos cropped. In the main menu and in submenus too. Please move it down.
![logo1-crop](https://user-images.githubusercontent.com/1296125/169090801-7a189822-395e-413e-a65e-9187f38783c7.PNG)
![logo2-crop](https://user-images.githubusercontent.com/1296125/169090804-91bfa51e-6746-4d03-b658-8c32481c31d9.PNG)

**Comment by fagnerpc** [comment]
Hey, [frodo19](https://github.com/frodo19)
This issue has been resolved in the last update.
Thanks for the feedback

**Comment by frodo19** [comment]
Thank you I will try it !
