### ISSUE TITLE
Some systems missing for Retrobat V5

### ISSUE THREAD

**Issue by getupor** [fagnerpc/Alekfull-ARTFLIX#19]
Ola Fagner

Just notice that 2 systems are missing :
megadrive-msu
neogeo64 (hyper NeoGeo 64)

Thanks a lot by advance

**Comment by fagnerpc** [comment]
Olá [getupor](https://github.com/getupor), how ur doing?
I added 35+ systems and collections in the last theme update and it includes the missing systems as you had noticed.

Thanks for the feedback :)
