### ISSUE TITLE
Border of the button to select an option is too dark.

### ISSUE THREAD

**Issue by ggr18** [fagnerpc/Alekfull-ARTFLIX#2]
The border of the buttons are dark, making them difficult to know wich one are you selecting. Can you add a red border (for example), or some way to change the colour of the button for emphasis?

![photo_2021-02-23_19-56-38](https://user-images.githubusercontent.com/20265995/108899206-12afd680-7610-11eb-98b4-e3e59cdba71d.jpg)

Emuelec V4.0, fresh install
Language: spanish

**Comment by Zot1881** [comment]
Same problem. Maybe if not doing this fix you can point what element change must be done for this issue?

**Comment by fagnerpc** [comment]
Button colors has changed in the last update.
