### ISSUE TITLE
Request: Lightgun Games, Steam

### ISSUE THREAD

**Issue by Lazorne** [fagnerpc/Alekfull-ARTFLIX#5]
Hello Batocera and others have enabled Steam support as a category.
I really love this theme and would love to have a image and background for Steam.
Another one I really miss is Lightgun Games. 

Thanks!

**Comment by fagnerpc** [comment]
Hey [Lazorne](https://github.com/Lazorne) :)
Steam and Lightgun systems have already been added to the theme in the latest updates.
