### ISSUE TITLE
Recalbox compatibility?

### ISSUE THREAD

**Issue by b1ack0p** [fagnerpc/Alekfull-ARTFLIX#6]
is it possible to use this super cool theme for Recalbox which is using Emulation Station also? I tried but it is causing freeze at boot splash screen after reboot.

**Comment by fagnerpc** [comment]
I've ported the theme to Recalbox... respecting the system's limitations.
Link: https://github.com/fagnerpc/Alekfull-ARTFLIX-Recalbox
